# Override default config
#

highlighter: rouge

theme: minimal-mistakes-jekyll

scholar:
   source: .
   style: simple-ieee.csl
   bibliography_template: bib
   bibliography_list_tag: "ul.no-bullet"

