# CI for jekyll-scholar-examples
language: ruby
sudo: false
cache: bundler
matrix:
  include:
  - rvm: 2.5
    #- rvm: 2.3
before_install: 
   - gem update --system ;
   - gem update bundler ;
install:
    bundle install ;
script:
   - bundle exec rake ;
   - bundle exec rake build_all;
   - cp -r /tmp/examples _site/
   - ls -l _site/ ;
deploy:
   provider: pages
   github-token: $GITHUB_API_KEY
   skip_cleanup: true
   local_dir: _site/
   keep-history: true
   branch: gh-pages 
   target-branch: gh-pages

