language: ruby
sudo: false
cache: bundler
matrix:
  include:
  - rvm: 2.5
    env: WITH_COVERALLS=false
  - rvm: 2.4
    env: WITH_COVERALLS=false
  - rvm: 2.3
    env: WITH_COVERALLS=false
install:
    bundle install ;
script:
    bundle exec rake 
notifications:
