# CI for jekyll-scholar-examples
language: ruby
sudo: false
cache: bundler
matrix:
  include:
  - rvm: 2.4
    #- rvm: 2.3
install:
    bundle install ;
script:
   bundle exec rake 
   #after_success:
   #   - if [[ $PAGES = "true" ]]; then
   #     mkdir www;
   #     cd www;
   #     git clone -b gh-pages git@github.com/rseac/jekyll-scholar-extras.git;
   #     cd jekyll-scholar-extras;
   #     git rm -rf . ;
   #     cp -r ../_site/examples . ;
   #     git add . ;
   #     git push -f -q https://rseac:$GITHUB_API_KEY@github.com/rseac/jekyll-scholar-examples-gh-pages gh-pages &2>/dev/null
   #
   #     git commit -m "Rendered jekyll-scholar-examples" ;
   #     git push -u origin gh-pages ;
   #     fi 
deploy:
   provider: pages
   github-token: $GITHUB_API_KEY
   skip_cleanup: true
   local_dir: _site/examples/
   keep-history: true
   on:
      branch: gh-pages 
   target-branch: gh-pages

