# CI for jekyll-scholar-examples
language: ruby
sudo: false
cache: bundler
matrix:
  include:
  - rvm: 2.4
    #- rvm: 2.3
install:
    bundle install ;
script:
   bundle exec rake 
deploy:
   provider: pages
   github-token: $GITHUB_API_KEY
   skip_cleanup: true
   local_dir: _site/examples/
   keep-history: true
   branch: gh-pages 
   target-branch: gh-pages

