# Override default config
#

highlighter: rouge

theme: minimal-mistakes-jekyll

url     : "https://rseac.github.io/" # 
baseurl : "/jekyll-scholar-examples" # 

scholar:
   source: .
   style: ./simple-ieee.csl
   bibliography_list_tag: "ul.no-bullet"

